[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.145.0"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[context.production.environment]
  HUGO_ENV = "production" 